name = "DataAssimilation"
uuid = "6bcffdd3-b48a-4009-8a26-82f832c94d30"
authors = ["John Waczak <john.louis.waczak@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
